title: Mohammed Shahebaz Madani
logo: /assets/img/Mine.jpg
description: 
<p>
<br> 
AI & ML enthusiast.
Persuaing Msc in AI & ML from LJMU & IIITB.
Certified SAP consultant with 15+ years of experience.
<br> 
</p>

email: shahebazmadani@gmail.com

theme: jekyll-theme-minimal
