title: Mohammed Shahebaz Madani
logo: /assets/img/Mine.jpg
description: 

AI & ML enthusiast.
Persuaing Msc in AI & ML from LJMU & IIITB.
Certified SAP consultant with 15+ years of experience.


theme: jekyll-theme-minimal
